github:
  api_url: https://api.github.com/repos/rawfunkmaharishi/rawfunkmaharishi.github.io/contents
  gig_path: gigs/_posts
  raw_url: https://raw.githubusercontent.com/rawfunkmaharishi/rawfunkmaharishi.github.io/master
  sounds_path: _data/soundcloud.yaml
  pictures_path: _data/flickr.yaml
  videos_path: _data/vimeo.yaml

rfm:
  base_url: http://rawfunkmaharishi.uk
  gig_path: gigs
