github:
  urls:
    api: https://api.github.com/repos/rawfunkmaharishi/rawfunkmaharishi.github.io/contents
    raw: https://raw.githubusercontent.com/rawfunkmaharishi/rawfunkmaharishi.github.io/master

  paths:
    gigs: gigs/_posts
    sounds: _data/soundcloud.yaml
    pictures: _data/flickr.yaml
    videos: _data/vimeo.yaml
    photographers: _data/photographers.yml

rfm:
  base_url: http://rawfunkmaharishi.uk
  gig_path: gigs
